theme: minima
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/lasleandro" }
    - { platform: twitter, user_url: "https://twitter.com/lasleandro" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=U8pfqkkAAAAJ&hl=pt-BR&authuser=1"}
